import { connectToDatabase } from "@/lib/mongodb";
import { Product } from "@/models/Product";
import { getProductDisplayImage } from "@/lib/product-images";

export type ProductItem = {
  title: string;
  slug: string;
  categorySlug: string;
  subCategory?: string;
  price: number;
  originalPrice?: number;
  discountPercent?: string;
  image: string;
  brand: string;
  rating: number;
  description?: string;
  inStock?: boolean;
  badge?: string;
  tags?: string[];
};

export const DEFAULT_PRODUCTS: ProductItem[] = [
  // ==========================================
  // 1. CLOTHES CATEGORY (clothes - Fashion 8 Products)
  // ==========================================
  {
    title: "Levi's 511 Slim Fit Stretch Denim Jeans",
    slug: "levis-511-slim-fit-jeans",
    categorySlug: "clothes",
    subCategory: "Bottoms & Pants",
    price: 49.99,
    originalPrice: 59.99,
    discountPercent: "16.6% OFF",
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&auto=format&fit=crop",
    brand: "LEVI'S",
    rating: 4.9,
    description: "Classic 5-pocket denim stretch jeans with modern slim fit cut and zip fly.",
    badge: "Best Seller",
    inStock: true,
    tags: ["32", "jeans", "cotton"],
  },
  {
    title: "H&M High-Waist Seamless Yoga Leggings",
    slug: "hm-high-waist-yoga-leggings",
    categorySlug: "clothes",
    subCategory: "Bottoms & Pants",
    price: 29.99,
    originalPrice: 34.99,
    discountPercent: "14.2% OFF",
    image: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600&auto=format&fit=crop",
    brand: "H&M",
    rating: 4.85,
    description: "Breathable moisture-wicking compression leggings designed for workout comfort.",
    badge: "Trending",
    inStock: true,
    tags: ["S", "leggings", "yoga"],
  },
  {
    title: "The North Face Premium Cotton Zip-Up Hoodie",
    slug: "north-face-cotton-zip-hoodie",
    categorySlug: "clothes",
    subCategory: "Tops & Outerwear",
    price: 69.99,
    originalPrice: 79.99,
    discountPercent: "12.5% OFF",
    image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&auto=format&fit=crop",
    brand: "THE NORTH FACE",
    rating: 4.95,
    description: "Heavyweight fleece lined cotton hoodie with adjustable drawstrings and front pouch.",
    badge: "Popular",
    inStock: true,
    tags: ["M", "hoodie", "cotton"],
  },
  {
    title: "Zara Women's Floral Summer Sundress",
    slug: "zara-womens-floral-sundress",
    categorySlug: "clothes",
    subCategory: "Women's Collection",
    price: 39.99,
    originalPrice: 45.99,
    discountPercent: "13.0% OFF",
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&auto=format&fit=crop",
    brand: "ZARA",
    rating: 4.8,
    description: "Lightweight A-line summer midi dress with sweetheart neckline and botanical print.",
    badge: "New Edit",
    inStock: true,
    tags: ["S", "dress", "floral"],
  },
  {
    title: "Ralph Lauren Classic Fit Piqué Polo Shirt",
    slug: "ralph-lauren-classic-polo-shirt",
    categorySlug: "clothes",
    subCategory: "Tops & Shirts",
    price: 59.99,
    originalPrice: 75.00,
    discountPercent: "20.0% OFF",
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop",
    brand: "RALPH LAUREN",
    rating: 4.88,
    description: "Breathable 100% cotton piqué knit polo shirt with signature embroidered pony accent.",
    badge: "Classic",
    inStock: true,
    tags: ["L", "polo", "cotton"],
  },
  {
    title: "AllSaints Premium Biker Leather Jacket",
    slug: "allsaints-biker-leather-jacket",
    categorySlug: "clothes",
    subCategory: "Outerwear & Jackets",
    price: 249.00,
    originalPrice: 299.00,
    discountPercent: "16.7% OFF",
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop",
    brand: "ALLSAINTS",
    rating: 4.92,
    description: "Butter-soft lambskin leather motorcycle jacket with asymmetrical zip and nickel hardware.",
    badge: "Luxury",
    inStock: true,
    tags: ["leather", "jacket", "biker"],
  },
  {
    title: "Ray-Ban Aviator Classic Gold Sunglasses",
    slug: "rayban-aviator-gold-sunglasses",
    categorySlug: "clothes",
    subCategory: "Luxury Accessories",
    price: 163.00,
    originalPrice: 185.00,
    discountPercent: "11.8% OFF",
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop",
    brand: "RAY-BAN",
    rating: 4.85,
    description: "Gold metal frame teardrop aviators featuring G-15 green polarized UV lenses.",
    badge: "Luxury",
    inStock: true,
    tags: ["UV400", "gold", "polarised"],
  },
  {
    title: "Calvin Klein Cotton Stretch Boxer Briefs 3-Pack",
    slug: "calvin-klein-boxer-briefs-3pack",
    categorySlug: "clothes",
    subCategory: "Underwear & Innerwear",
    price: 34.99,
    originalPrice: 42.50,
    discountPercent: "17.6% OFF",
    image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&auto=format&fit=crop",
    brand: "CALVIN KLEIN",
    rating: 4.85,
    description: "Soft breathable cotton stretch boxer briefs with signature logo elastic waistband.",
    badge: "Essential",
    inStock: true,
    tags: ["cotton", "3-pack", "black"],
  },

  // ==========================================
  // FOOTWEAR COLLECTION (8 Products)
  // ==========================================
  {
    title: "Nike Air Force 1 '07 Low White Sneakers",
    slug: "nike-air-force-1-sneakers",
    categorySlug: "shoes",
    subCategory: "Footwear",
    price: 110.00,
    originalPrice: 125.00,
    discountPercent: "12.0% OFF",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop",
    brand: "NIKE",
    rating: 4.9,
    description: "Iconic leather low-top sneakers with perforated toe cap and durable rubber outsole.",
    badge: "Exclusive",
    inStock: true,
    tags: ["US 9", "leather", "white"],
  },
  {
    title: "Adidas Ultraboost Light Running Shoes",
    slug: "adidas-ultraboost-light-shoes",
    categorySlug: "shoes",
    subCategory: "Footwear",
    price: 139.99,
    originalPrice: 169.99,
    discountPercent: "17.6% OFF",
    image: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600&auto=format&fit=crop",
    brand: "ADIDAS",
    rating: 4.95,
    description: "Lightweight responsive running sneakers with Primeknit upper and Boost midsole cushioning.",
    badge: "Top Rated",
    inStock: true,
    tags: ["Boost", "running", "black"],
  },
  {
    title: "Puma EvoSpeed Track Spikes Athletic Shoes",
    slug: "puma-evospeed-track-spikes",
    categorySlug: "shoes",
    subCategory: "Footwear",
    price: 54.99,
    originalPrice: 69.99,
    discountPercent: "21.4% OFF",
    image: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600&auto=format&fit=crop",
    brand: "PUMA",
    rating: 4.8,
    description: "Sprint track spike running shoes with aerodynamic synthetic upper and 8-spike plate.",
    badge: "Sport Edit",
    inStock: true,
    tags: ["spikes", "orange", "sprint"],
  },
  {
    title: "Converse Chuck Taylor All Star High Top",
    slug: "converse-chuck-taylor-high-top",
    categorySlug: "shoes",
    subCategory: "Footwear",
    price: 49.99,
    originalPrice: 60.00,
    discountPercent: "16.7% OFF",
    image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&auto=format&fit=crop",
    brand: "CONVERSE",
    rating: 4.88,
    description: "Timeless canvas high-top sneakers with rubber toe cap and star ankle patch.",
    badge: "Heritage",
    inStock: true,
    tags: ["canvas", "high-top", "white"],
  },
  {
    title: "Timberland 6-Inch Premium Waterproof Winter Boots",
    slug: "timberland-6inch-waterproof-boots",
    categorySlug: "shoes",
    subCategory: "Footwear",
    price: 159.00,
    originalPrice: 189.00,
    discountPercent: "15.8% OFF",
    image: "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=600&auto=format&fit=crop",
    brand: "TIMBERLAND",
    rating: 4.94,
    description: "Rugged waterproof nubuck leather boots with seam-sealed construction and rustproof hardware.",
    badge: "Winter Gear",
    inStock: true,
    tags: ["boots", "leather", "wheat"],
  },
  {
    title: "Vans Old Skool Classic Canvas Skate Shoes",
    slug: "vans-old-skool-canvas-shoes",
    categorySlug: "shoes",
    subCategory: "Footwear",
    price: 44.99,
    originalPrice: 55.00,
    discountPercent: "18.2% OFF",
    image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&auto=format&fit=crop",
    brand: "VANS",
    rating: 4.82,
    description: "Classic side-stripe low top skate shoes with durable suede and canvas uppers.",
    badge: "Skate Edit",
    inStock: true,
    tags: ["skate", "black", "canvas"],
  },
  {
    title: "Speedo Aqua Water Beach Shoes for Adults",
    slug: "speedo-aqua-water-beach-shoes",
    categorySlug: "shoes",
    subCategory: "Footwear",
    price: 19.99,
    originalPrice: 24.99,
    discountPercent: "20.0% OFF",
    image: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600&auto=format&fit=crop",
    brand: "SPEEDO",
    rating: 4.75,
    description: "Quick-drying neoprene mesh water shoes with non-slip rubber grip sole.",
    badge: "Beach Deal",
    inStock: true,
    tags: ["water", "beach", "aqua"],
  },
  {
    title: "Clarks Leather Platform Loafer Shoes",
    slug: "clarks-leather-platform-loafers",
    categorySlug: "shoes",
    subCategory: "Footwear",
    price: 79.99,
    originalPrice: 95.00,
    discountPercent: "15.8% OFF",
    image: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600&auto=format&fit=crop",
    brand: "CLARKS",
    rating: 4.87,
    description: "Handcrafted full-grain leather platform slip-on loafers with cushioned OrthoLite footbed.",
    badge: "Comfort",
    inStock: true,
    tags: ["loafers", "leather", "platform"],
  },

  // ==========================================
  // 2. FURNITURE CATEGORY (furniture)
  // ==========================================
  {
    title: "Herman Miller Aeron Ergonomic Mesh Chair",
    slug: "herman-miller-aeron-chair",
    categorySlug: "furniture",
    subCategory: "Ergonomic Seating",
    price: 495.00,
    originalPrice: 590.00,
    discountPercent: "16.1% OFF",
    image: "https://images.unsplash.com/photo-1505797149-43b0069ec26b?w=600&auto=format&fit=crop",
    brand: "HERMAN MILLER",
    rating: 4.95,
    description: "Iconic Pellicle 8Z breathable mesh executive office chair with PostureFit SL lumbar.",
    badge: "Top Rated",
    inStock: true,
    tags: ["mesh", "lumbar", "office"],
  },
  {
    title: "IKEA Modern Japanese White Oak Coffee Table",
    slug: "ikea-oak-coffee-table",
    categorySlug: "furniture",
    subCategory: "Artisan Tables",
    price: 180.00,
    originalPrice: 210.00,
    discountPercent: "14.2% OFF",
    image: "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=600&auto=format&fit=crop",
    brand: "IKEA",
    rating: 4.8,
    description: "Solid white oak minimalist low coffee table with oil finish and rounded edges.",
    badge: "Best Seller",
    inStock: true,
    tags: ["oak", "wood", "table"],
  },
  {
    title: "West Elm Ambient Touch Dimmable Desk Lamp",
    slug: "west-elm-ceramic-desk-lamp",
    categorySlug: "furniture",
    subCategory: "Ambient Lighting",
    price: 125.00,
    originalPrice: 145.00,
    discountPercent: "13.7% OFF",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&auto=format&fit=crop",
    brand: "WEST ELM",
    rating: 4.75,
    description: "Handcrafted matte ceramic base lamp with 2700K warm LED touch-dimmer switch.",
    badge: "Minimal",
    inStock: true,
    tags: ["LED", "ceramic", "lamp"],
  },
  {
    title: "Kube Modular Velvet Lounge Sectional Sofa",
    slug: "kube-velvet-sectional-sofa",
    categorySlug: "furniture",
    subCategory: "Living & Bedroom",
    price: 899.00,
    originalPrice: 1050.00,
    discountPercent: "14.3% OFF",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&auto=format&fit=crop",
    brand: "KUBE",
    rating: 4.9,
    description: "Deep plush velvet 3-piece modular sectional couch in slate grey with hardwood frame.",
    badge: "Luxury",
    inStock: true,
    tags: ["velvet", "sofa", "slate"],
  },

  // ==========================================
  // 3. UTENSILS CATEGORY (utensils)
  // ==========================================
  {
    title: "Zwilling J.A. Henckels 8-Inch Chef Knife",
    slug: "zwilling-damascus-chef-knife",
    categorySlug: "utensils",
    subCategory: "Chef Knives",
    price: 145.00,
    originalPrice: 175.00,
    discountPercent: "17.1% OFF",
    image: "https://images.unsplash.com/photo-1593618998160-e34014e67546?w=600&auto=format&fit=crop",
    brand: "ZWILLING",
    rating: 4.95,
    description: "67-layer Japanese VG-10 Damascus stainless steel knife with ergonomic handle.",
    badge: "Chef Choice",
    inStock: true,
    tags: ["VG-10", "steel", "8-inch"],
  },
  {
    title: "Le Creuset Enamelled Dutch Oven 5.5 Qt",
    slug: "le-creuset-dutch-oven",
    categorySlug: "utensils",
    subCategory: "Cookware Sets",
    price: 280.00,
    originalPrice: 330.00,
    discountPercent: "15.1% OFF",
    image: "https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=600&auto=format&fit=crop",
    brand: "LE CREUSET",
    rating: 4.9,
    description: "Heavyweight enamelled cast iron Dutch oven with lid for braising, stewing & baking.",
    badge: "Best Seller",
    inStock: true,
    tags: ["cast iron", "5.5qt", "red"],
  },
  {
    title: "Cuisinart 24-Piece Matte Black Cutlery Set",
    slug: "cuisinart-cutlery-set",
    categorySlug: "utensils",
    subCategory: "Luxury Tableware",
    price: 89.00,
    originalPrice: 105.00,
    discountPercent: "15.2% OFF",
    image: "https://images.unsplash.com/photo-1615865417491-9941019fbc00?w=600&auto=format&fit=crop",
    brand: "CUISINART",
    rating: 4.8,
    description: "Titanium electroplated matte black 18/10 stainless steel dining cutlery flatware set.",
    badge: "Popular",
    inStock: true,
    tags: ["18/10 steel", "black", "24-pcs"],
  },

  // ==========================================
  // 4. MEDICAL CATEGORY (medical - 8 Products)
  // ==========================================
  {
    title: "Omron Bluetooth Upper Arm BP Monitor",
    slug: "omron-bluetooth-bp-monitor",
    categorySlug: "medical",
    subCategory: "Clinical Diagnostics",
    price: 69.99,
    originalPrice: 84.99,
    discountPercent: "17.6% OFF",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop",
    brand: "OMRON",
    rating: 4.9,
    description: "Clinical grade digital blood pressure reader with smartphone Bluetooth synchronization.",
    badge: "FDA Cleared",
    inStock: true,
    tags: ["BP", "bluetooth", "clinical"],
  },
  {
    title: "Theragun Pro Deep Tissue Massage Gun",
    slug: "theragun-pro-massage-gun",
    categorySlug: "medical",
    subCategory: "Mobility & Rehab",
    price: 249.00,
    originalPrice: 299.00,
    discountPercent: "16.7% OFF",
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&auto=format&fit=crop",
    brand: "THERAGUN",
    rating: 4.9,
    description: "QuietForce brushless motor recovery percussion gun with 6 swappable head attachments.",
    badge: "Top Rated",
    inStock: true,
    tags: ["brushless", "rehab", "6-heads"],
  },
  {
    title: "Beurer Fingertip Pulse Oximeter & Heart Rate Monitor",
    slug: "beurer-fingertip-pulse-oximeter",
    categorySlug: "medical",
    subCategory: "Clinical Diagnostics",
    price: 29.99,
    originalPrice: 39.99,
    discountPercent: "25.0% OFF",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&auto=format&fit=crop",
    brand: "BEURER",
    rating: 4.88,
    description: "Non-invasive SpO2 oxygen saturation and pulse measurement with OLED color display.",
    badge: "Clinical",
    inStock: true,
    tags: ["SpO2", "pulse", "oximeter"],
  },
  {
    title: "Braun No-Touch Infrared Forehead Thermometer",
    slug: "braun-infrared-forehead-thermometer",
    categorySlug: "medical",
    subCategory: "Clinical Diagnostics",
    price: 44.99,
    originalPrice: 55.00,
    discountPercent: "18.2% OFF",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop",
    brand: "BRAUN",
    rating: 4.92,
    description: "Precision infrared fever guidance thermometer with color-coded back-lit display.",
    badge: "Pediatric",
    inStock: true,
    tags: ["infrared", "fever", "thermometer"],
  },
  {
    title: "Philips HEPA Medical Grade Air Purifier Series 2000i",
    slug: "philips-hepa-medical-air-purifier",
    categorySlug: "medical",
    subCategory: "Respiratory Care",
    price: 199.00,
    originalPrice: 249.00,
    discountPercent: "20.0% OFF",
    image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&auto=format&fit=crop",
    brand: "PHILIPS",
    rating: 4.9,
    description: "NanoProtect HEPA filter capturing 99.97% of airborne allergens, viruses & dust particles.",
    badge: "Allergy Care",
    inStock: true,
    tags: ["HEPA", "air purifier", "philips"],
  },
  {
    title: "Bauerfeind GenuTrain Compression Knee Support",
    slug: "bauerfeind-genutrain-knee-support",
    categorySlug: "medical",
    subCategory: "Mobility & Orthopedics",
    price: 89.00,
    originalPrice: 105.00,
    discountPercent: "15.2% OFF",
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&auto=format&fit=crop",
    brand: "BAUERFEIND",
    rating: 4.86,
    description: "Medical grade targeted compression knee brace with Omega pad stabilization.",
    badge: "Orthopedic",
    inStock: true,
    tags: ["knee", "brace", "compression"],
  },
  {
    title: "Littmann Classic III Monitoring Stethoscope",
    slug: "littmann-classic-iii-stethoscope",
    categorySlug: "medical",
    subCategory: "Clinical Diagnostics",
    price: 119.00,
    originalPrice: 139.00,
    discountPercent: "14.4% OFF",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&auto=format&fit=crop",
    brand: "3M LITTMANN",
    rating: 4.98,
    description: "Dual-sided chestpiece acoustic stethoscope designed for adult and pediatric monitoring.",
    badge: "Doctor Choice",
    inStock: true,
    tags: ["stethoscope", "3M", "medical"],
  },
  {
    title: "Tempur-Pedic Ergonomic Memory Foam Neck Pillow",
    slug: "tempur-pedic-neck-pillow",
    categorySlug: "medical",
    subCategory: "Sleep & Wellness",
    price: 79.00,
    originalPrice: 99.00,
    discountPercent: "20.2% OFF",
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&auto=format&fit=crop",
    brand: "TEMPUR-PEDIC",
    rating: 4.89,
    description: "Contoured ergonomic memory foam cervical support pillow for spinal alignment.",
    badge: "Wellness",
    inStock: true,
    tags: ["pillow", "memory foam", "neck"],
  },

  // ==========================================
  // 5. COSMETICS CATEGORY (cosmetics)
  // ==========================================
  {
    title: "L'Oréal Revitalift Hyaluronic Serum 30ml",
    slug: "loreal-hyaluronic-serum",
    categorySlug: "cosmetics",
    subCategory: "Skincare Essentials",
    price: 28.99,
    originalPrice: 34.99,
    discountPercent: "17.1% OFF",
    image: "https://images.unsplash.com/photo-1608248597266-c896505f6142?w=600&auto=format&fit=crop",
    brand: "L'ORÉAL",
    rating: 4.9,
    description: "1.5% pure Hyaluronic Acid serum for intense skin hydration and wrinkle reduction.",
    badge: "Best Seller",
    inStock: true,
    tags: ["30ml", "serum", "hyaluronic"],
  },
  {
    title: "Dior Sauvage Eau de Parfum Spray 100ml",
    slug: "dior-sauvage-parfum",
    categorySlug: "cosmetics",
    subCategory: "Luxury Fragrances",
    price: 145.00,
    originalPrice: 165.00,
    discountPercent: "12.1% OFF",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&auto=format&fit=crop",
    brand: "DIOR",
    rating: 4.95,
    description: "Artisanal Eau de Parfum infused with Calabrian bergamot, Sichuan pepper & amber wood.",
    badge: "Exclusive",
    inStock: true,
    tags: ["100ml", "parfum", "dior"],
  },

  // ==========================================
  // 6. FOOD CATEGORY (food)
  // ==========================================
  {
    title: "Borges Extra Virgin Tuscan Olive Oil 1L",
    slug: "borges-extra-virgin-olive-oil",
    categorySlug: "food",
    subCategory: "Gourmet Oils & Pantry",
    price: 24.99,
    originalPrice: 29.99,
    discountPercent: "16.6% OFF",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop",
    brand: "BORGES",
    rating: 4.9,
    description: "Cold-pressed single origin extra virgin olive oil harvested from Italian olive groves.",
    badge: "Organic",
    inStock: true,
    tags: ["cold pressed", "1L", "Tuscan"],
  },
  {
    title: "Lavazza Specialty Whole Bean Coffee 1kg",
    slug: "lavazza-whole-bean-coffee",
    categorySlug: "food",
    subCategory: "Fine Beverages",
    price: 28.00,
    originalPrice: 34.00,
    discountPercent: "17.6% OFF",
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600&auto=format&fit=crop",
    brand: "LAVAZZA",
    rating: 4.85,
    description: "100% Arabica medium roast specialty coffee beans with floral & honey notes.",
    badge: "Artisanal",
    inStock: true,
    tags: ["Arabica", "1kg", "coffee"],
  },

  // ==========================================
  // 7. SMART DEVICES CATEGORY (smart-devices - 8 Products)
  // ==========================================
  {
    title: "Sony WH-1000XM5 Wireless ANC Headphones",
    slug: "sony-wh1000xm5-headphones",
    categorySlug: "smart-devices",
    subCategory: "Audiophile Sound",
    price: 348.00,
    originalPrice: 399.00,
    discountPercent: "12.7% OFF",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop",
    brand: "SONY",
    rating: 4.95,
    description: "Industry-leading active noise canceling wireless headphones with 30-hour battery life.",
    badge: "Best Seller",
    inStock: true,
    tags: ["ANC", "30h battery", "black"],
  },
  {
    title: "Apple Watch Series 9 GPS 45mm Titanium",
    slug: "apple-watch-series-9",
    categorySlug: "smart-devices",
    subCategory: "Wearable Tech",
    price: 429.00,
    originalPrice: 499.00,
    discountPercent: "14.0% OFF",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop",
    brand: "APPLE",
    rating: 4.9,
    description: "S9 SiP smartwatch with double-tap gesture control, ECG and blood oxygen sensor.",
    badge: "New Tech",
    inStock: true,
    tags: ["45mm", "OLED", "titanium"],
  },
  {
    title: "Anker 737 Power Bank 24,000mAh 140W",
    slug: "anker-737-power-bank-140w",
    categorySlug: "smart-devices",
    subCategory: "Power & Chargers",
    price: 99.99,
    originalPrice: 129.99,
    discountPercent: "23.0% OFF",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop",
    brand: "ANKER",
    rating: 4.91,
    description: "3-port ultra-powerful 140W fast portable charger with smart digital color display.",
    badge: "Fast Charge",
    inStock: true,
    tags: ["140W", "24000mAh", "anker"],
  },
  {
    title: "Logitech MX Master 3S Wireless Ergonomic Mouse",
    slug: "logitech-mx-master-3s-mouse",
    categorySlug: "smart-devices",
    subCategory: "Computer Accessories",
    price: 89.99,
    originalPrice: 99.99,
    discountPercent: "10.0% OFF",
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop",
    brand: "LOGITECH",
    rating: 4.96,
    description: "8K DPI track-anywhere quiet click precision wireless mouse with MagSpeed electromagnetic wheel.",
    badge: "Pro Choice",
    inStock: true,
    tags: ["8K DPI", "mouse", "logitech"],
  },
  {
    title: "JuiceBox Level 2 40A Fast EV Charger",
    slug: "juicebox-fast-ev-charger",
    categorySlug: "smart-devices",
    subCategory: "EV Charging Tech",
    price: 329.00,
    originalPrice: 389.00,
    discountPercent: "15.4% OFF",
    image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=600&auto=format&fit=crop",
    brand: "JUICEBOX",
    rating: 4.85,
    description: "40A 240V smart EV charging station with OLED screen & NEMA 14-50 plug.",
    badge: "Fast Charge",
    inStock: true,
    tags: ["40A", "240V", "EV"],
  },
  {
    title: "Anker Nebula Capsule 3 Laser 1080p Projector",
    slug: "anker-nebula-capsule-3-projector",
    categorySlug: "smart-devices",
    subCategory: "Home Entertainment",
    price: 699.00,
    originalPrice: 799.00,
    discountPercent: "12.5% OFF",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop",
    brand: "ANKER NEBULA",
    rating: 4.89,
    description: "Handheld mini 300 ANSI lumen 1080p laser smart projector with Google TV.",
    badge: "4K Laser",
    inStock: true,
    tags: ["1080p", "projector", "nebula"],
  },
  {
    title: "Belkin BoostCharge Pro 3-in-1 MagSafe Wireless Charger",
    slug: "belkin-boostcharge-3in1-magsafe",
    categorySlug: "smart-devices",
    subCategory: "Power & Chargers",
    price: 129.99,
    originalPrice: 149.99,
    discountPercent: "13.3% OFF",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop",
    brand: "BELKIN",
    rating: 4.87,
    description: "Official 15W fast wireless MagSafe stand for iPhone, Apple Watch & AirPods.",
    badge: "MagSafe",
    inStock: true,
    tags: ["15W", "magsafe", "belkin"],
  },
  {
    title: "Arlo Pro 4 Spotlight 2K Wireless Security Camera",
    slug: "arlo-pro-4-spotlight-security-camera",
    categorySlug: "smart-devices",
    subCategory: "Smart Home Security",
    price: 179.99,
    originalPrice: 199.99,
    discountPercent: "10.0% OFF",
    image: "https://images.unsplash.com/photo-1557324232-b8917d3c3dcb?w=600&auto=format&fit=crop",
    brand: "ARLO",
    rating: 4.84,
    description: "2K HDR outdoor wireless security camera with integrated spotlight and color night vision.",
    badge: "Security",
    inStock: true,
    tags: ["2K", "camera", "arlo"],
  },
];

export async function getProductsByCategory(categorySlug: string): Promise<ProductItem[]> {
  const normSlug = categorySlug.toLowerCase().trim();
  try {
    await connectToDatabase();
    const productsFromDb = await Product.find(
      { categorySlug: normSlug },
      { _id: 0, __v: 0, createdAt: 0, updatedAt: 0 }
    )
      .sort({ price: 1 })
      .lean();

    if (productsFromDb && productsFromDb.length > 0) {
      return productsFromDb.map((prod) => {
        const title = String(prod.title);
        const image = prod.image
          ? String(prod.image)
          : getProductDisplayImage({ image: undefined, categorySlug: normSlug, title, brand: String(prod.brand) });
        
        return {
          title,
          slug: String(prod.slug),
          categorySlug: String(prod.categorySlug),
          subCategory: prod.subCategory ? String(prod.subCategory) : "General",
          price: Number(prod.price),
          originalPrice: prod.originalPrice ? Number(prod.originalPrice) : Math.round(Number(prod.price) * 1.18 * 100) / 100,
          discountPercent: prod.discountPercent ? String(prod.discountPercent) : "15% OFF",
          image,
          brand: String(prod.brand),
          rating: Number(prod.rating),
          description: prod.description ? String(prod.description) : "",
          inStock: prod.inStock !== undefined ? Boolean(prod.inStock) : true,
          badge: prod.badge ? String(prod.badge) : "",
          tags: prod.tags ? (prod.tags as string[]) : ["popular", "in-stock"],
        };
      });
    }

    // Fallback: return default products for this category Slug
    const filteredDefaults = DEFAULT_PRODUCTS.filter((p) => p.categorySlug === normSlug).map((prod) => ({
      ...prod,
      image: getProductDisplayImage(prod),
    }));

    return filteredDefaults.length > 0 ? filteredDefaults : DEFAULT_PRODUCTS.slice(0, 8);
  } catch (error) {
    console.warn("MongoDB product query notice:", error instanceof Error ? error.message : error);
    const filteredDefaults = DEFAULT_PRODUCTS.filter((p) => p.categorySlug === normSlug).map((prod) => ({
      ...prod,
      image: getProductDisplayImage(prod),
    }));
    return filteredDefaults.length > 0 ? filteredDefaults : DEFAULT_PRODUCTS.slice(0, 8);
  }
}
